### ISSUE TITLE
Migração de dados - novos campos da UP

### ISSUE THREAD

**Issue by alantygel** [coletivoEITA/SMUL-SisRural#102]
As issues #89 a #101 detalham novos campos no formulário da Unidade Produtiva. Após a implementação, é necessário verificar quais dessas alterações vão ocasionar perda de dados e precisará ser feita uma migração. Esta migração pode ser manual ou automática.

- [ ] #90 - É preciso migrar os dados do campo similar que existe no formulário (Solos (características gerais)). migração automática
- [ ] #92 - Há um campo similar no formulário (Cultivos existentes - quantidade - situação produtiva), porém a migração tem que ser manual.
- [ ] #86 - Está em outro bloco mas atenção: foram retiradas as opções relacionadas a resíduo orgânico da pergunta sobre resíduos sólidos em geral. verificar se alguém marcou elas e transferir.

**Comment by alantygel** [comment]
Migração das características do solo feita com esse script: 

```
$ups = UnidadeProdutivaModel::all();
foreach($ups as $up){ 
    $solo = UnidadeProdutivaRespostaModel::where('pergunta_id', 18)->where('unidade_produtiva_id', $up->id)->first(); 
    if($solo){
        $up->caracteristica_solo = $solo->resposta;
        $up->save();
        echo $up->id . "\n";
    }
}
